### ISSUE TITLE
nodata when reset rows[] object

### ISSUE THREAD

**Issue by istiti** [swimlane/angular2-data-table#136]
BUG:
This component works well when no scroll but when I scroll and change rows[] data with ajax call no data are displayed, here you are:  click this gif
![error when change data](https://cloud.githubusercontent.com/assets/2789203/18711969/95b6e6c6-800c-11e6-84aa-38bc75e8033c.gif)

The <datatable> is one  for all tab, I juste reset rows data. How can achieve this bug ? Is there better way to update datarows or?

FACULTATIF: you can see when waiting data I set `rows=[]`empty and I have header and emptyMessage "No data to display" instead of nothing... I don't think I can use something like style display:hide  when `rows.length==0`

**Comment by amcdnl** [comment]
Can you build a demo w/ plunkr?

**Comment by istiti** [comment]
I can't, I have so many  module but I have only one datatable tag and his rows[] is different... but when scrolling it wont works with another rows[]  update ... very strange

**Comment by amcdnl** [comment]
I'm sorry w/o a demo, I won't be able to help.

**Comment by istiti** [comment]
hmm? Close my issue like this isn't very cool. Since when a demo is mandatory to check if a library contain bug? I come with signifiant GIF you can't reproduce this yourself not for me but for community. And if i'm doing some wrong we would know ... I just reset rows data if you need teamviewer to check you are welcome

**Comment by amcdnl** [comment]
Awesome, I will check it out today!

Sorry, I closed it but without proper reproduction I can't make a fix ;).

**Comment by amiller29au** [comment]
I noticed same issue while trying to get around [https://github.com/swimlane/angular2-data-table/issues/127](url)

I was delaying the the setting of the rows object bound to the datatable in ngAfterViewInit() to see if this worked, but it didn't I got message 'No data Loaded'.

**Comment by amcdnl** [comment]
Is this resolved by the other PR?

**Comment by istiti** [comment]
@amcdnl I posted a plunker, do you checked it ? http://plnkr.co/edit/k7JBaZottJUhtOdgfW1P?p=preview

The problem is always here on my plunker ! 

But today I have another problem: you can check it here on my GIF, you will see the content of the table is fill only until middle ... not completly... maybe because of "display:none" nefore data is available.... the problem is here:
**MIDDLE EMPTY PROBLEM:**
![datatable-middle-empty](https://cloud.githubusercontent.com/assets/2789203/18942294/33697918-8618-11e6-9d5e-d481aa955088.gif)

Another things or ENHANCEMENT please putt the scroll bar in TOP:0 when we change data... you can see on this next gif that if I scroll bottom and change TAB so the scrollbar keep same position instead of going TOP !!!

**SCROLLBAR PROBLEM:**
![datatable-scrollbar](https://cloud.githubusercontent.com/assets/2789203/18942343/98247ede-8618-11e6-96b3-2ccf76e89840.gif)

**Comment by amcdnl** [comment]
Ya, agreed I think it should reset scrollbar position to the top on a re-sort.

**Comment by istiti** [comment]
@amcdnl What do you mean "re-sort" Because I just reset data I don't sort them on clicking on column, I think the scrollbar need go position to top when this is changing: **[rows]='dataFiles'**

**Comment by amcdnl** [comment]
Fixed the sort not updating scrollbar in 0.7.4

**Comment by istiti** [comment]
@amcdnl my friend please apologize but not fixed! I have one more same question do you checked my demo here http://plnkr.co/edit/k7JBaZottJUhtOdgfW1P?p=preview 
You can see the problem with these step: 
The problem is when you click **Get data 1** (scroll a little bit down...) THEN click Get data 2 => SURPRISE ! No data or data aren't reset on GET DATA 2 and whenyou go back to GET DATA 1 it still empty

**Comment by amcdnl** [comment]
Is this still happening?

**Comment by istiti** [comment]
donno can't retry now but will close it and reopen it if still happen, thanks

**Comment by Tazzmanian** [comment]
it still happens. if i show 10 rows per page and go on page 2, then change the table.bodyHeight (table height via css) the scroll is at top but first 10 rows space is blank and the second part is visible. It shows the data on scroll down, because scroll up is not possible. If it is done from page 1 there is no such problem.
