### ISSUE TITLE
Table page not updated after filtering.

### ISSUE THREAD

**Issue by xhagrg** [swimlane/angular2-data-table#141]
I went through and implemented it for myself, the filtering using the example. It seems that the page is not reset when filtering. 
Steps to reproduce:
1. Go to any page other than the first page.
2. Filter using any name from the first page.
3. Total records found shows correct count, but no rows are shown.

I might be missing something. Can we reset the page back to 1 after filtering?

**Comment by amcdnl** [comment]
Please create a demo use case.

**Comment by xhagrg** [comment]
@amcdnl , the examples/demos provided on the website i.e. https://plnkr.co/edit/bvA2gMHyxFtCFN8ZWbi0?p=info contains the bug.
1. First page contains the name `Valarie`
<img width="634" alt="screen shot 2016-09-26 at 9 11 27 am" src="https://cloud.githubusercontent.com/assets/4485278/18837435/64af0c0a-83c9-11e6-8eaa-3632a5730975.png">
<img width="579" alt="screen shot 2016-09-26 at 9 11 50 am" src="https://cloud.githubusercontent.com/assets/4485278/18837479/831ec766-83c9-11e6-8280-be2d7c76003b.png">
2. Navigate to page 2.
<img width="577" alt="screen shot 2016-09-26 at 9 12 05 am" src="https://cloud.githubusercontent.com/assets/4485278/18837491/8ba61a06-83c9-11e6-8496-b956a78fb371.png">
3. Search for `Valarie`
<img width="570" alt="screen shot 2016-09-26 at 9 12 13 am" src="https://cloud.githubusercontent.com/assets/4485278/18837507/99a34f0c-83c9-11e6-93cd-5528f68194a5.png">
The total count at the bottom says it found the record, but there is no records displayed.

**Comment by xhagrg** [comment]
@amcdnl anything on this?

**Comment by Anuovec** [comment]
What is the status on this?

**Comment by striff** [comment]
I have the exact same issue. Please help us fix this.

**Comment by vijayanandkannan** [comment]
I have exactly the same issue. Can you please let us know how to reset to the first page

**Comment by Rezi** [comment]
Same issue. This should be prioritised, as it is a major bug.

**Comment by web265p3** [comment]
Is anybody working on that? Its a very important feature and I wont use the table if this cannot be fixed... :(

**Comment by istiti** [comment]
I have same problem with updating row event dispatchEvent resize don't works !

**Comment by amcdnl** [comment]
@istiti - i believe i fixed this, can u verify?

**Comment by xhagrg** [comment]
@amcdnl It seems the issue still persists, see the following screenshot:
<img width="1440" alt="screen shot 2016-12-06 at 12 00 08 am" src="https://cloud.githubusercontent.com/assets/4485278/20914717/22d2df22-bb47-11e6-9577-d33d4bec890c.png">

**Comment by web265p3** [comment]
For me its not fixed neither...

**Comment by rajeshvaya** [comment]
is this issue fixed?

**Comment by yadejo** [comment]
The datatable component has an `@Input() offset` and an `@Output() page.` You can use these to keep track of the pagination and reset the page when the data changes.

**Comment by xhagrg** [comment]
Looks like @yadejo 's approach will work. Closing the issue now.

**Comment by allenan** [comment]
@yadejo do you have an example of how to access and set the data table's offset?

**Comment by rajeshvaya** [comment]
@allenan 
This way works for me:

```HTML
<swui-datatable
        class="material" 
        [rows]="rows"
        [columns]="columns"
        [limit]="5"
        [offset]="currentPage"
        (page)="onChange($event)"
    >
```


```Javascript
export class MyComponent {
   // your component declaration code to define rows and columns with data

    currentPage: number = 0; // set the current page to one (the value is page - 1)

    // when a page is changed by the user, below even is triggered and since there is no 3 way binding, the currentPage var needs to be set to the new value
    onChange(event: any): void {
        this.currentPage = event.offset;
    }
}

```

**Comment by nhducseuit** [comment]
Setting offset to 0 doesn't make the table scroll to top. the offsetY is not 0 but 540 so that the scroll bar is not on top but bottom.
Also DataTableBodyComponent.updateOffsetY(0) isn't able to change offsetY from 540 to 0.
