### ISSUE TITLE
Dragging doesn't work

### ISSUE THREAD

**Issue by jtomaszewski** [swimlane/angular2-data-table#178]
**Current behavior**
You can drag the header columns, but the body column stay untouched.

**Expected behavior**
After finishing the drag movement, body columns should be reodered if needed.

**Reproduction of the problem**
The bug is easily reproduciable on current master.

**NOTES**

After a bit of debugging, seems like the events from 'draggable' are not emitted into 'orderable' directive. `this.drags` is empty when it subscribes to the events. I tried using `this.drags.changes.subscribe(() => { ... }` instead, but it doesnt help at all. 

Any ideas how to fix it?

**Comment by amcdnl** [comment]
Was this addressed in a PR?

**Comment by jtomaszewski** [comment]
No, I didnt make anything to fix it yet.

**Comment by khurambutt-REIsys** [comment]
I found exactly the same problem, added a new issue in the issue queue as I missed this one from the issue list when I searched for existing issue regarding this, sorry about that.

My debugging took me to the exact same spot, this.drags is empty which makes the events from 'draggable' not emitted to 'orderable'. Any possible fix for this guys?

By the way, great work on the project.

**Comment by amcdnl** [comment]
This should be fixed in latest, I do not see it happening

**Comment by RohitRane** [comment]
This still happens if use custom template like 
<ng-template let-column="column" let-sort="sortFn" ngx-datatable-header-template>
                <i class="fa fa-filter clickable" (click)="showColFilter(col, $event)"></i>
                <span class="clickable col-title" (click)="sort()">{{column.name}}</span>
            </ng-template>

If I remove this drag works !
