### ISSUE TITLE
Client-side paging continues after last page

### ISSUE THREAD

**Issue by Helayxa** [swimlane/angular2-data-table#223]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

My table has 10 pages. If I am on page 10 and click on the right arrow to go to the next page, it's not disabled (although the cursor has changed for an interdiction), and I got an empty list of page numbers.

**Expected behavior**

If I have 10 pages and that I am on page 10, I shouldn't be able to click on the right arrow to go to next page.

**Reproduction of the problem**

http://plnkr.co/edit/DAvtelilZMTRKj0vopxC
Just add a limit: 10 option.

Thanks in advance.

**Comment by amcdnl** [comment]
Fixed in 1.4.1 :)

**Comment by striff** [comment]
It's not fixed. I updated the npm package and I still have this issue.
