### ISSUE TITLE
Column Toggling.

### ISSUE THREAD

**Issue by RonnyLV** [swimlane/angular2-data-table#245]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```

Column Toggling fails at some point.

**Reproduction of the problem**
Using Demo page on toggling demo, try to toggle all columns multiple times and it will fail with Exception "EXCEPTION: Cannot read property 'dragStart' of null"

* **Table version:** 1.0.0
* **Browser:** [ Chrome Version 54.0.2840.71 m (64-bit) ]

**Comment by amcdnl** [comment]
I tested this before deploy. Thanks for reporting will check it out.

**Comment by amcdnl** [comment]
Ah, its clicking the same one bunch of times. I hate this approach I had to do, I'm looking for a better way.

**Comment by amcdnl** [comment]
Fixed in 1.3.0

**Comment by DmitryEfimenko** [comment]
This is still an issue in the demo. Not sure what version the demo is using
