### ISSUE TITLE
Async Problem when using @Input as data source

### ISSUE THREAD

**Issue by Codermar** [swimlane/angular2-data-table#253]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

After upgrading to 1.1 I am getting the error error_handler.js:47 EXCEPTION: Error in ./DataTableBodyComponent class DataTableBodyComponent - inline template:14:8 caused by: Cannot read property 'length' of null

This happens when I pass the data via Input from another component.

My dumb component has:
            <datatable
              class="material"
              [rows]="rowData"
              [columns]="columns"
              [columnMode]="'force'"
              [headerHeight]="50"
              [footerHeight]="50"
              [rowHeight]="'auto'">
            </datatable>

where "rowData" is passed via @Input
@Input() rowData: Array<Workaround> = [];

I can see my data in the component if I output it {{ rowData | json }} (I should mention that I am using ngrx and that I just updated to angular 2.2.0-rc.0

**Expected behavior**

It should display the data correctly as it did on v 0.11

**Reproduction of the problem**

Reproducible plunkr http://plnkr.co/edit/PrGJLIVC3FMGa3BqOTxw?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Mac OS, angular-cli beta 19.3

* **Table version:** 1.1

* **Angular version:** 2.2.0-rc.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by shattar** [comment]
I think it just means that your row data is null.  Are you sure it is never null?  This happened to me too so I just made sure to replace null or undefined row data with an empty array.

That being said, this component should probably be robust to null or undefined rows.

**Comment by Codermar** [comment]
You can actually see it reproduced here now http://plnkr.co/edit/PrGJLIVC3FMGa3BqOTxw?p=preview

**Comment by shattar** [comment]
That's not really a fair reproduction is it?  You have an error that is unrelated to datatable when you try to call `push` on an undefined property called `rows`.  Line 50 of app.ts.  Also, since `this.rows` is undefined, it also leads to it not having a member called `length`.  If you declare and initialize `this.rows` as an empty array, it might work.

**Comment by Codermar** [comment]
My bad on the undefined rows, however, I edited the plunkr, defined the rows, then passed it and there's no error now but the data does not display... am I missing something? The code was actually running on 0.11...

**Comment by shattar** [comment]
Now it seems to be displaying for me when I view your plunkr with Chrome on Windows.  However, there is the `ExpressionChangedAfterItHasBeenCheckedError`.  This is caused because datatable modifies your provided rows and `{{ rows | json }}` really doesn't like it when datatable side-swipes the rows array, but that's a different problem.  If you remove the `{{ rows | json }}`, does it work in your browser?

**Comment by Codermar** [comment]
It does work at the plunkr... However,  I've revisited my other code and I am still getting the error. This may have to do with the observable not returning the data by the time the component is initialized and so I tend to think the internal handling of datatable still has some kind of async issue... The only difference I see in my code is that I am using ngrx to retrieve the data in the parent component as in:
public rowData: Array<Workaround> = [];
....
      this.store.let(getIssueRelatedWorkarounds()).subscribe(workarounds => this.rowData = workarounds);
      this.store.dispatch(this.issueWorkaroundActions.loadIssueRelatedWorkarounds(this.issueId));

**Comment by amcdnl** [comment]
Why not do this?

```
<datatable [rows]='rows | async'></datatable>
```

**Comment by Codermar** [comment]
I have tried that with no luck.

**Comment by Codermar** [comment]
Ok, my workaround for the time being is:

      this.store.let(getIssueRelatedWorkarounds())
        .map(data => data || []) // prevent datatable null error
        .subscribe(workarounds => {
        this.rowData = <Workaround[]>workarounds;
      });
      this.store.dispatch(this.issueWorkaroundActions.loadIssueRelatedWorkarounds(this.issueId));`
`
I still feel this should be handled internally by datatables...

**Comment by Codermar** [comment]
Revisiting this after a while I also noticed the following error when I enabled storefreeze in ngRx

error_handler.js:47 EXCEPTION: Error in ./DatatableComponent class DatatableComponent - inline template:25:8 caused by: Can't add property $$index, object is not extensible

This is because Datatables is mutating the data being passed to it. Perhaps this could also be addressed by the the component as well.

My workaround for the time being is:

`
  store.let(getIssueRelatedWorkarounds()).subscribe(workarounds => {
        // I need this to prevent datatables from mutating the data
        this.rowData = JSON.parse(JSON.stringify(<Workaround[]>workarounds));
  });
`

**Comment by amcdnl** [comment]
Fixed in 1.7.0

**Comment by Codermar** [comment]
I am not sure what was fixed but this continues to be an issue with ngrx store freeze. I am forced to pass a copy of the data to prevent mutation.

**Comment by amcdnl** [comment]
@Codermar - see my rx demo...are u using it differently? Can u help us repo this in a demo project?

**Comment by ethanve** [comment]
I am also having this issue. I'm using ngrx/store and ngrx-store-freeze. I followed your rx example and just passed the observable in the rows input. Still not working. No errors, but the data isnt showing up

**Comment by Codermar** [comment]
I'll share my workaround:

In my scenario, I have a smart component that calls a dumb component to render the datatable

Smart component:
```
...
export class EngneedsListComponent implements OnInit {

  searchQuery$: Observable<string>;
  rowData$: Observable<EngineeringNeed[]>;
  rowData: Array<EngineeringNeed>; // need this extra var to deep copy the data
  loading$: Observable<boolean>;
  itemRoute: string = '';

  constructor( private router: Router,
               private store: Store<fromRoot.State>,
               private service: EngneedsService ) {
    this.searchQuery$ = store.let(fromRoot.getEngNeedSearchQuery).take(1);
    this.rowData$ = store.let(fromRoot.getEngNeedSearchResults);
    this.loading$ = store.let(fromRoot.getEngNeedSearchLoading);
  }

  ngOnInit() {
   // I need this extra step so I can pass this.rowData (deep copy) to the dumb component
    this.rowData$.subscribe(engNeeds => {
      // prevent datatables from mutating the data
      this.rowData = JSON.parse(JSON.stringify(<EngineeringNeed[]>engNeeds)); 
    });
    this.store.dispatch(new action.LoadAllAction());
  }
}
```
In the template:
```
          <aui-engneed-table-list
            [rowData]="rowData" // note in here I could not do [rowData]="rowData$ | async"
            (onEdit)="onEdit($event)"
            (onDelete)="onDelete($event)"></aui-engneed-table-list>
```
In the dumb component: (aui-engneed-table-list)
```
... 
@Input() rowData: Array<EngineeringNeed> = [];
...
        <datatable
          class='material datatable fixed-header fixed-row scroll-vertical'
          [rows]='rowData'
          [columnMode]="'force'"
          [headerHeight]="50"
          [footerHeight]="0"
          [rowHeight]="50"
          [scrollbarV]="true"
          [scrollbarH]="true">
         .... my columns here ...
</datatable>
```
@amcdnl The issue has to do with data mutation of the passed rows object. I'll try to come up with a plunker but it requires quite a bit of work to reproduce it exactly.

**Comment by ethanve** [comment]
I think it would be great if we kept the row data immutable and have some other internal array holding on to the meta data (such as the `$$index`)?

**Comment by amcdnl** [comment]
I'm working on this, hoping to have a patch today.

**Comment by amcdnl** [comment]
Fixed in 2.0

**Comment by Codermar** [comment]
Thank you for the 2.0 release but I am afraid the storeFreeze issue is still there... I just updated, enabled storeFreeze for ngrx and got the same error. As I mentioned before, my workaround is disabling storeFreeze for local but it would be nice if they could play together.

**Comment by amcdnl** [comment]
Yes plz 🤔

**Comment by h4mit** [comment]
use async pipe in the package version 2.1.3 show error my project.
 code : 
```
rows: Observable<ContactBook[]>;

  constructor(private cgService: ContactBookService) {
  }

  ngOnInit(): void {
    this.rows = this.cgService.getContactBooks();
  }
``` 
template : 
```
<swui-datatable
          class="material"
          [rows]="rows | async"
          [columnMode]="'force'"
          [headerHeight]="50"
          [footerHeight]="50"
          [rowHeight]="'auto'"
          [limit]="10">
    <swui-datatable-column name="name">
      <template let-column="column" swui-datatable-header-template>
         {{column.name}}
      </template>
      <template let-value="value" swui-datatable-cell-template>
       <strong>{{value}}</strong>
      </template>
    </swui-datatable-column>
    <swui-datatable-column name="type">
      <template let-column="column" swui-datatable-header-template>
         {{column.name}}
      </template>
      <template let-value="value" swui-datatable-cell-template>
        <strong>{{'CONTACT_GROUP.'+value | translate}}</strong>
      </template>
    </swui-datatable-column>
  </swui-datatable>
```

error : 
```
 core.umd.js:3004 EXCEPTION: Uncaught (in promise): Error: Error in ./DatatableComponent class DatatableComponent - inline template:15:8 caused by: Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at DatatableComponent.get [as allRowsSelected] (http://localhost:3000/node_modules/angular2-data-table/release/index.js:2174:54)
    at _View_DatatableComponent1.detectChangesInternal (/Angular2DataTableModule/DatatableComponent/component.ngfactory.js:330:42)
    at _View_DatatableComponent1.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9305:18)
    at _View_DatatableComponent1.DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9410:48)
    at _View_DatatableComponent0.AppView.detectContentChildrenChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9323:23)
    at _View_DatatableComponent0.detectChangesInternal (/Angular2DataTableModule/DatatableComponent/component.ngfactory.js:192:8)
    at _View_DatatableComponent0.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9305:18)
    at _View_DatatableComponent0.DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9410:48)
    at _View_ContactGroup0.AppView.detectViewChildrenChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9331:23)
    at _View_ContactGroup0.detectChangesInternal (/PageModule/ContactGroup/component.ngfactory.js:203:8)ErrorHandler.handleError @ core.umd.js:3004next @ core.umd.js:6654schedulerFn @ core.umd.js:5952SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238SafeSubscriber.next @ Subscriber.ts:190Subscriber._next @ Subscriber.ts:135Subscriber.next @ Subscriber.ts:95Subject.next @ Subject.ts:61EventEmitter.emit @ core.umd.js:5944NgZone.triggerError @ core.umd.js:6248onHandleError @ core.umd.js:6227ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131_loop_1 @ zone.js:412drainMicroTaskQueue @ zone.js:421ZoneTask.invoke @ zone.js:339
core.umd.js:3009 ORIGINAL STACKTRACE:ErrorHandler.handleError @ core.umd.js:3009next @ core.umd.js:6654schedulerFn @ core.umd.js:5952SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238SafeSubscriber.next @ Subscriber.ts:190Subscriber._next @ Subscriber.ts:135Subscriber.next @ Subscriber.ts:95Subject.next @ Subject.ts:61EventEmitter.emit @ core.umd.js:5944NgZone.triggerError @ core.umd.js:6248onHandleError @ core.umd.js:6227ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131_loop_1 @ zone.js:412drainMicroTaskQueue @ zone.js:421ZoneTask.invoke @ zone.js:339
core.umd.js:3010 Error: Uncaught (in promise): Error: Error in ./DatatableComponent class DatatableComponent - inline template:15:8 caused by: Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at DatatableComponent.get [as allRowsSelected] (datatable.component.ts:653)
    at _View_DatatableComponent1.detectChangesInternal (component.ngfactory.js:330)
    at _View_DatatableComponent1.AppView.detectChanges (core.umd.js:9305)
    at _View_DatatableComponent1.DebugAppView.detectChanges (core.umd.js:9410)
    at _View_DatatableComponent0.AppView.detectContentChildrenChanges (core.umd.js:9323)
    at _View_DatatableComponent0.detectChangesInternal (component.ngfactory.js:192)
    at _View_DatatableComponent0.AppView.detectChanges (core.umd.js:9305)
    at _View_DatatableComponent0.DebugAppView.detectChanges (core.umd.js:9410)
    at _View_ContactGroup0.AppView.detectViewChildrenChanges (core.umd.js:9331)
    at _View_ContactGroup0.detectChangesInternal (component.ngfactory.js:203)
    at resolvePromise (zone.js:468)
    at zone.js:445
    at ZoneDelegate.invoke (zone.js:232)
    at Object.onInvoke (core.umd.js:6206)
    at ZoneDelegate.invoke (zone.js:231)
    at Zone.run (zone.js:114)
    at zone.js:502
    at ZoneDelegate.invokeTask (zone.js:265)
    at Object.onInvokeTask (core.umd.js:6197)
    at ZoneDelegate.invokeTask (zone.js:264)ErrorHandler.handleError @ core.umd.js:3010next @ core.umd.js:6654schedulerFn @ core.umd.js:5952SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238SafeSubscriber.next @ Subscriber.ts:190Subscriber._next @ Subscriber.ts:135Subscriber.next @ Subscriber.ts:95Subject.next @ Subject.ts:61EventEmitter.emit @ core.umd.js:5944NgZone.triggerError @ core.umd.js:6248onHandleError @ core.umd.js:6227ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131_loop_1 @ zone.js:412drainMicroTaskQueue @ zone.js:421ZoneTask.invoke @ zone.js:339
zone.js:388 Unhandled Promise rejection: Error in ./DatatableComponent class DatatableComponent - inline template:15:8 caused by: Cannot read property 'length' of null ; Zone: angular ; Task: Promise.then ; Value: ViewWrappedError {_nativeError: Error: Error in ./DatatableComponent class DatatableComponent - inline template:15:8 caused by: Cann…, originalError: TypeError: Cannot read property 'length' of null
    at DatatableComponent.get [as allRowsSelected] …, context: DebugContext} TypeError: Cannot read property 'length' of null
    at DatatableComponent.get [as allRowsSelected] (http://localhost:3000/node_modules/angular2-data-table/release/index.js:2174:54)
    at _View_DatatableComponent1.detectChangesInternal (/Angular2DataTableModule/DatatableComponent/component.ngfactory.js:330:42)
    at _View_DatatableComponent1.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9305:18)
    at _View_DatatableComponent1.DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9410:48)
    at _View_DatatableComponent0.AppView.detectContentChildrenChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9323:23)
    at _View_DatatableComponent0.detectChangesInternal (/Angular2DataTableModule/DatatableComponent/component.ngfactory.js:192:8)
    at _View_DatatableComponent0.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9305:18)
    at _View_DatatableComponent0.DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9410:48)
    at _View_ContactGroup0.AppView.detectViewChildrenChanges (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9331:23)
    at _View_ContactGroup0.detectChangesInternal (/PageModule/ContactGroup/component.ngfactory.js:203:8)consoleError @ zone.js:388_loop_1 @ zone.js:417drainMicroTaskQueue @ zone.js:421ZoneTask.invoke @ zone.js:339
zone.js:390 Error: Uncaught (in promise): Error: Error in ./DatatableComponent class DatatableComponent - inline template:15:8 caused by: Cannot read property 'length' of null(…)
```

**Comment by amcdnl** [comment]
@MikeRyan52 any thoughts on the above? ^^

**Comment by BafS** [comment]
I have the same problem with async data but I just wrapped the table with an ngIf

```js
<div *ngIf="playlist.tracks">
  <swui-datatable [rows]="playlist.tracks" ...></swui-datatable>
</div>
```

**Comment by gregkopp** [comment]
I'll add to this. Using "@swimlane/angular-data-table 4.0.0" I am experiencing the same issue with storeFreeze. Once I disable it, I get data loaded in the table. Disabling storeFreeze is a much less than ideal solution, however.

**Comment by Codermar** [comment]
Although not ideal, an alternative to not disabling storeFreeze is what I mentioned in https://github.com/swimlane/ngx-datatable/issues/253#issuecomment-264022087
I have a "half-there" plunker to reproduce the issue for the datatable team. I'll try to finalize it soon.

**Comment by gregkopp** [comment]
I gave your workaround a try. I thought about doing this myself, and didn't want to initially, because I consider it a hack. BUT, it keeps me moving forward on this until something changes. THANKS!

**Comment by pchristou** [comment]
@Codermar thanks for the workaround. I see that this issue has been closed, is there another open one which discusses a "native" fix?

**Comment by gregkopp** [comment]
I moved on. I found PrimeNG which provides a datatable that is compatible with storeFreeze.

**Comment by Codermar** [comment]
pchristou I was going to open a new issue for that. I just haven't had the chance to get the plunker ready to reproduce it, in the meantime there's a new version of datatable which I have not tried but it seems to have issues of its own so I am taking a few days to decide which course of action to take. gregkopp: i do agree that was a "hack" and that a native solution is in order. Thanks for the tip on PrimeNG, it looks promising...

**Comment by amcdnl** [comment]
@gregkopp - Sorry to hear you moved on, best of luck. I've looked at Prime before, sadly they didn't have virtualized dom at the time.

Sadly, I tried a all on-push setup in 2.0 but many others had trouble. After lengthy discussion with @MikeRyan52 we decided its probably best to do it like this. I did learn that if your parent component implements on push it transcends all the way down.

If you have a fully working example, it would be much easier to help resolve the problem.

**Comment by amcdnl** [comment]
This PR should take care of the mutations that were causing store freeze to not work. https://github.com/swimlane/ngx-datatable/pull/623

**Comment by RicardoVaranda** [comment]
@amcdnl Don't mean to rush but just wondering when this is going to be released as I have the same use case, storeFreeze is causing the object is not extensible issue.

**Comment by amcdnl** [comment]
Sadly, I had to back this change out due to regressions. I'll be on vaca next week but this is on my list as I'm moving to ngrx-store soon.

**Comment by mattma** [comment]
I use the latest version `9.2.0` with Redux (ngrx) and `ngrx-store-freeze` module. I run into the same issue. It is easy producible since the original JSON object has been modified with `index$$: ...` and other keys/values.

Is there a timeline on when this feature will be landed?
Is there a hack that I can use without removing **freeze store** function check?

**Comment by real-artswan** [comment]
It seems the problem still here in 9.3.0

**Comment by mattma** [comment]
Should we reopen this issue and track the right status?

**Comment by vance** [comment]
So weird, i have freeze but didn't get a freeze error... plus, this kind of breaks the nice template convention of 
`[rows]="someRows$ | async" `
there's no good way to copy data at this point.

**Comment by mattma** [comment]
you must not enable the freeze somehow. are you sure that you register the freeze via `metaReducer`. Anyway, the issue still exsits. See [my concern](https://github.com/swimlane/ngx-datatable/pull/764#issuecomment-317517175)  thinking of using `angular-material/cdk` instead. :( if the support is there, that would be great.
