### ISSUE TITLE
Don't seem able to pre-select rows on loading a component.

### ISSUE THREAD

**Issue by nickraphael** [swimlane/angular2-data-table#366]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I've tried using the 'selected' property to pre-select the first row when the component first loads.  But the row does not appear to be selected.  

**Expected behavior**
I would have expected to set 'selected' and the datatable should have called the select event for that row.  The row should also appear to be selected (eg. highlighted in blue)

**Comment by amcdnl** [comment]
Resolved in latest, even made demo

**Comment by damluk82** [comment]
Can you please give us an url, where to find the demo or some explanation to this feature?
I tried to find it, but it I just cant able to find anything.

Thank you for your help.

**Comment by DrackThor** [comment]
Hi @amcdnl can you please give us an URL on where to find the mentioned example?
I'm still facing this issue with version 16.0.3 and haven't found any example on this requirement online.
